<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="14910" started-at="2019-10-18T09:25:33Z" finished-at="2019-10-18T09:25:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="14910" started-at="2019-10-18T09:25:33Z" finished-at="2019-10-18T09:25:48Z">
      <class name="com.newtours.tests.LoginTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.newtours.tests.LoginTests@32eebfca]" name="setup" is-config="true" duration-ms="4789" started-at="2019-10-18T09:25:33Z" finished-at="2019-10-18T09:25:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="verifyTitleOfThePage()[pri:0, instance:com.newtours.tests.LoginTests@32eebfca]" name="verifyTitleOfThePage" duration-ms="11" started-at="2019-10-18T09:25:37Z" finished-at="2019-10-18T09:25:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTitleOfThePage -->
        <test-method status="PASS" signature="afterEveryTestCase(org.testng.ITestResult)[pri:0, instance:com.newtours.tests.LoginTests@32eebfca]" name="afterEveryTestCase" is-config="true" duration-ms="2" started-at="2019-10-18T09:25:37Z" finished-at="2019-10-18T09:25:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyTitleOfThePage status=SUCCESS method=LoginTests.verifyTitleOfThePage()[pri:0, instance:com.newtours.tests.LoginTests@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEveryTestCase -->
        <test-method status="FAIL" signature="verifyLoginToNewTours()[pri:1000, instance:com.newtours.tests.LoginTests@32eebfca]" name="verifyLoginToNewTours" duration-ms="9163" started-at="2019-10-18T09:25:37Z" finished-at="2019-10-18T09:25:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.newtours.tests.LoginTests.verifyLoginToNewTours(LoginTests.java:36)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginToNewTours -->
        <test-method status="PASS" signature="afterEveryTestCase(org.testng.ITestResult)[pri:0, instance:com.newtours.tests.LoginTests@32eebfca]" name="afterEveryTestCase" is-config="true" duration-ms="301" started-at="2019-10-18T09:25:47Z" finished-at="2019-10-18T09:25:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyLoginToNewTours status=FAILURE method=LoginTests.verifyLoginToNewTours()[pri:1000, instance:com.newtours.tests.LoginTests@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEveryTestCase -->
        <test-method status="PASS" signature="cleanUp()[pri:0, instance:com.newtours.tests.LoginTests@32eebfca]" name="cleanUp" is-config="true" duration-ms="619" started-at="2019-10-18T09:25:47Z" finished-at="2019-10-18T09:25:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
        <test-method status="PASS" signature="postCleanup()[pri:0, instance:com.newtours.tests.LoginTests@32eebfca]" name="postCleanup" is-config="true" duration-ms="289" started-at="2019-10-18T09:25:48Z" finished-at="2019-10-18T09:25:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postCleanup -->
      </class> <!-- com.newtours.tests.LoginTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
